export const Questions = [
    {
        topic: "Redux",
        prompt: "What is 1+3",
        optionA: "24",
        optionB: "21",
        optionC: "4",
        optionD: "2",
        answer: "C",
    },
    {
        topic: "Redux",
        prompt: "Which is a Streaming Platform?",
        optionA: "Twitter",
        optionB: "Twitch",
        optionC: "Google",
        optionD: "Robinhood",
        answer: "B",
    },
    {
        topic: "Redux",
        prompt: "Best tech youtube channel?",
        optionA: "PedroTech",
        optionB: "Jordan",
        optionC: "Cassano",
        optionD: "Adda",
        answer: "B",
    },
    {
        topic: "Redux",
        prompt: "What the best rock band?",
        optionA: "Guns N Roses",
        optionB: "Queen",
        optionC: "Iron Maiden",
        optionD: "Metallica",
        answer: "A",
    },
    {
        topic: "React",
        prompt: "What is the answer to the life?",
        optionA: "34",
        optionB: "42",
        optionC: "1",
        optionD: "6",
        answer: "B",
    },
    {
        topic: "Javascript",
        prompt: "What is best drink?",
        optionA: "Water",
        optionB: "Coca-Cola",
        optionC: "Pepsi",
        optionD: "Thè",
        answer: "A",
    }
]
